lasso:
  constructor: {}
  fit: {}
  tuning_hyperparams: {}
logisticRegression:
  constructor:
    C: 0.21808262011647106
  fit: {}
  tuning_hyperparams:
    C:
      type: float
      vals:
      - 0
      - 1
logisticRegressionBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams: {}
nn:
  constructor:
    batch_size: 10000
    dropout: -1
    epochs: 1000
    hidden_layers:
    - 32
  fit: {}
  tuning_hyperparams: {}
nnBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams: {}
svm:
  constructor:
    C: 0.1
    gamma: 0.1
  fit: {}
  tuning_hyperparams: {}
xgb:
  constructor:
    colsample_bylevel: 0.9
    colsample_bytree: 0.8
    gamma: 1.7544
    learning_rate: 0.11692
    max_delta_step: 10
    max_depth: 4
    min_child_weight: 3
    objective: binary:logistic
    reg_alpha: 0
    reg_lambda: 1
    seed: 4
    silent: 1
    subsample: 0.9
  fit:
    eval_metric: auc
    verbose: true
  tuning_hyperparams:
    gamma:
      type: float
      vals:
      - 1.5
      - 2.5
    learning_rate:
      type: float
      vals:
      - 0.05
      - 0.15
    max_depth:
      type: int
      vals:
      - 3
      - 7
    min_child_weight:
      type: int
      vals:
      - 1
      - 7
xgbBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams:
    n_estimators:
      type: int
      vals:
      - 5
      - 10
xgbHist:
  constructor: 
    tree_method: gpu_hist
    eta: 0.3
    min_child_weight: 1
    max_depth: 6
    max_leaf_nodes: 4
    gamma: 0
    max_delta_step: 0
    subsample: 1
    colsample_bytree: 1
    colsample_bylevel: 1
    alpha: 0
    lambda: 1
  fit: {}
  tuning_hyperparams:
    gamma:
      type: float
      vals:
      - 0
      - 5
    learning_rate:
      type: float
      vals:
      - 0.05
      - 0.15
    max_depth:
      type: int
      vals:
      - 1
      - 30
    min_child_weight:
      type: int
      vals:
      - 1
      - 30
 
