lasso:
  constructor: {}
  fit: {}
  tuning_hyperparams: {}
lgbm:
  constructor:
    learning_rate: 0.20485960115223173
    min_child_weight: 5
    n_estimators: 27
    num_leaves: 30
  fit:
    eval_metric: auc
  tuning_hyperparams:
    learning_rate:
      type: float
      vals:
      - 0.05
      - 0.3
    min_child_weight:
      type: int
      vals:
      - 1
      - 7
    n_estimators:
      type: int
      vals:
      - 10
      - 30
    num_leaves:
      type: int
      vals:
      - 10
      - 100
logisticRegression:
  constructor:
    C: 0.21808262011647106
  fit: {}
  tuning_hyperparams:
    C:
      type: float
      vals:
      - 0
      - 1
logisticRegressionBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams: {}
nn:
  constructor:
    batch_size: 200
    dropout: 0
    epochs: 100
    hidden_layers:
    - 64
    - 64
  fit: {}
  tuning_hyperparams: {}
nnBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams: {}
randomForest:
  constructor: {}
  fit: {}
  tuning_hyperparams: {}
svm:
  constructor:
    C: 0.1
    gamma: 0.1
  fit: {}
  tuning_hyperparams: {}
xgb:
  constructor:
    colsample_bylevel: 0.9
    colsample_bytree: 0.8
    gamma: 1.7544
    learning_rate: 0.11692
    max_delta_step: 10
    max_depth: 4
    min_child_weight: 3
    objective: binary:logistic
    reg_alpha: 0
    reg_lambda: 1
    seed: 4
    silent: 1
    subsample: 0.9
  fit:
    eval_metric: auc
    verbose: true
  tuning_hyperparams:
    gamma:
      type: float
      vals:
      - 1.5
      - 2.5
    learning_rate:
      type: float
      vals:
      - 0.05
      - 0.15
    max_depth:
      type: int
      vals:
      - 3
      - 7
    min_child_weight:
      type: int
      vals:
      - 1
      - 7
xgbBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams:
    n_estimators:
      type: int
      vals:
      - 5
      - 10
xgbHist:
  constructor:
    colsample_bylevel: 0.9
    colsample_bytree: 0.8
    gamma: 0.3557179036025354
    learning_rate: 0.18467506873989986
    max_delta_step: 0
    max_depth: 5
    max_leaf_nodes: 160
    min_child_weight: 12
    reg_alpha: 0
    reg_lambda: 1
    subsample: 0.9
    tree_method: hist
  fit: {}
  tuning_hyperparams:
    gamma:
      type: float
      vals:
      - 0
      - 5
    learning_rate:
      type: float
      vals:
      - 0.05
      - 0.25
    max_depth:
      type: int
      vals:
      - 1
      - 15
    max_leaf_nodes:
      type: int
      vals:
      - 1
      - 200
    min_child_weight:
      type: int
      vals:
      - 1
      - 30
lgbmBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams:
    n_estimators:
      type: int
      vals:
      - 5
      - 10

