nn:
  constructor:
    batch_size: 64
    epochs: 1000
  fit: {}
svm:
  constructor:
    C: 0.1
    gamma: 0.1
  fit: {}
xgb:
  constructor:
    learning_rate: 0.05
    silent: 1
    seed: 4
    objective: "binary:logistic"
    min_child_weight: 5
    colsample_bytree: 0.8
    colsample_bylevel: 0.9
    max_depth: 6
    subsample: 0.9
    max_delta_step: 10
    gamma: 2
    reg_alpha: 0
    reg_lambda: 1
  fit:
    eval_metric: auc
xgbBagged:
  constructor:
    n_estimators: 2
  fit: {}
