logisticRegression:
  constructor: {}
  fit: {}
  tuning_hyperparams: {}
logisticRegressionBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams: {}
nn:
  constructor:
    batch_size: 10
    epochs: 1
  fit: {}
nnBagged:
  constructor:
    n_estimators: 2
  fit: {}
  tuning_hyperparams: {}
svm:
  constructor:
    C: !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - f8
      - 0
      - 1
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      RFqgQZ8ViEA=
    gamma: 0.1
  fit: {}
  tuning_hyperparams:
    C:
      type: float
      vals:
      - 0.1
      - 0.1
      - 1
      - 10
      - 100
      - 1000
xgb:
  constructor:
    colsample_bylevel: 0.9
    colsample_bytree: 0.8
    gamma: 2.5
    learning_rate: 0.05
    max_delta_step: 10
    max_depth: 5
    min_child_weight: 3
    objective: binary:logistic
    reg_alpha: 0
    reg_lambda: 1
    seed: 4
    silent: 1
    subsample: 0.9
  fit:
    eval_metric: auc
    verbose: true
  tuning_hyperparams: {}
xgbBagged:
  constructor:
    n_estimators: 2
  fit: {}
