lasso:
  constructor: {}
  fit: {}
  tuning_hyperparams: {}
logisticRegression:
  constructor: {}
  fit: {}
  tuning_hyperparams: {}
logisticRegressionBagged:
  constructor:
    n_estimators: 5
  fit: {}
  tuning_hyperparams: {}
nn:
  constructor:
    batch_size: 10
    dropout: -1
    epochs: 1
    hidden_layers:
    - 1
  fit: {}
nnBagged:
  constructor:
    n_estimators: 2
  fit: {}
  tuning_hyperparams: {}
randomForest:
  constructor: {}
  fit: {}
  tuning_hyperparams: {}
svm:
  constructor:
    C: 865.709432428989
    gamma: 0
  fit: {}
  tuning_hyperparams:
    C:
      type: float
      vals:
      - 0.1
      - 1000
    gamma:
      type: int
      vals:
      - 0
      - 1
test:
  constructor:
    v: 0.6977709912591094
  fit: {}
  tuning_hyperparams:
    v:
      type: float
      vals:
      - 0
      - 1
xgb:
  constructor:
    colsample_bylevel: 0.9
    colsample_bytree: 0.8
    gamma: 2.085847249121714
    learning_rate: 0.05
    max_delta_step: 10
    max_depth: 5
    min_child_weight: 3
    objective: binary:logistic
    reg_alpha: 0
    reg_lambda: 1
    seed: 4
    silent: 1
    subsample: 0.9
  fit:
    eval_metric: auc
    verbose: true
  tuning_hyperparams:
    gamma:
      type: float
      vals:
      - 0
      - 4
xgbBagged:
  constructor:
    n_estimators: 2
  fit: {}
xgbHist:
  constructor:
    gamma: 0.5039375842491984
    tree_method: gpu_hist
  fit: {}
  tuning_hyperparams:
    gamma:
      type: float
      vals:
      - 0
      - 4
